apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: calculus-rag

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - ollama.yaml
  - app.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: calculus-rag
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
